
#kubectl taint node ip-10-0-0-24  perf=low:NoSchedule

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ENV
                operator: In
                values:
                - prod
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

     
